pipeline {
  agent any

  parameters{
   string(name: 'NAME', description: 'Enter yout name', defaultValue: 'Hanuman') 
  }

  stages{
    stage('Greetings'){
      steps{
        echo "Hello ${params.NAME}"
      }
    }
  }
}
